In [1]:
import pandas as pd

In [2]:
coc_fips_df = pd.read_csv('county_coc_source.csv')
coc_fips_df.head(10)

   FIPS    county state  number
0  1001   Autauga    AL  AL-507
1  1003   Baldwin    AL  AL-501
2  1005   Barbour    AL  AL-507
3  1007      Bibb    AL  AL-507
4  1009    Blount    AL  AL-503
5  1011   Bullock    AL  AL-507
6  1013    Butler    AL  AL-507
7  1015   Calhoun    AL  AL-505
8  1017  Chambers    AL  AL-507
9  1019  Cherokee    AL  AL-503

In [3]:
population_county_df = pd.read_csv('co-est2019-annres_clean.csv')
population_county_df.head(10)

,Geographic Area,FIPS,County,2010_population,2011_population,2012_population,2013_population,2014_population,2015_population,2016_population,2017_population,2018_population,2019_population
0,United States,NaN,NaN,"309,321,666","311,556,874","313,830,990","315,993,715","318,301,008","320,635,163","322,941,311","324,985,539","326,687,501","328,239,523"
1,".Autauga County, Alabama",1001.0,Autauga,"54,773","55,227","54,954","54,727","54,893","54,864","55,243","55,390","55,533","55,869"
2,".Baldwin County, Alabama",1003.0,Baldwin,"183,112","186,558","190,145","194,885","199,183","202,939","207,601","212,521","217,855","223,234"
3,".Barbour County, Alabama",1005.0,Barbour,"27,327","27,341","27,169","26,937","26,755","26,283","25,806","25,157","24,872","24,686"
4,".Bibb County, Alabama",1007.0,Bibb,"22,870","22,745","22,667","22,521","22,553","22,566","22,586","22,550","22,367","22,394"
5,".Blount County, Alabama",1009.0,Blount,"57,376","57,560","57,580","57,619","57,526","57,526","57,494","57,787","57,771","57,826"
6,".Bullock County, Alabama",1011.0,Bullock,"10,876","10,675","10,606","10,549","10,663","10,400","10,389","10,176","10,174","10,101"
7,".Butler County, Alabama",1013.0,Butler,"20,932","20,866","20,670","20,356","20,327","20,162","20,012","19,888","19,631","19,448"
8,".Calhoun County, Alabama",1015.0,Calhoun,"118,408","117,744","117,190","116,471","115,917","115,469","114,973","114,710","114,331","113,605"
9,".Chambers County, Alabama",1017.0,Chambers,"34,122","34,033","34,104","34,139","33,977","33,996","33,745","33,707","33,600","33,254"

In [4]:
county_coc_fips_df = pd.merge(coc_fips_df, population_county_df, left_on=['FIPS'], right_on=['FIPS'], how='left')
county_coc_fips_df.head(10)

,FIPS,county,state,number,Geographic Area,County,2010_population,2011_population,2012_population,2013_population,2014_population,2015_population,2016_population,2017_population,2018_population,2019_population
0,1001,Autauga,AL,AL-507,".Autauga County, Alabama",Autauga,"54,773","55,227","54,954","54,727","54,893","54,864","55,243","55,390","55,533","55,869"
1,1003,Baldwin,AL,AL-501,".Baldwin County, Alabama",Baldwin,"183,112","186,558","190,145","194,885","199,183","202,939","207,601","212,521","217,855","223,234"
2,1005,Barbour,AL,AL-507,".Barbour County, Alabama",Barbour,"27,327","27,341","27,169","26,937","26,755","26,283","25,806","25,157","24,872","24,686"
3,1007,Bibb,AL,AL-507,".Bibb County, Alabama",Bibb,"22,870","22,745","22,667","22,521","22,553","22,566","22,586","22,550","22,367","22,394"
4,1009,Blount,AL,AL-503,".Blount County, Alabama",Blount,"57,376","57,560","57,580","57,619","57,526","57,526","57,494","57,787","57,771","57,826"
5,1011,Bullock,AL,AL-507,".Bullock County, Alabama",Bullock,"10,876","10,675","10,606","10,549","10,663","10,400","10,389","10,176","10,174","10,101"
6,1013,Butler,AL,AL-507,".Butler County, Alabama",Butler,"20,932","20,866","20,670","20,356","20,327","20,162","20,012","19,888","19,631","19,448"
7,1015,Calhoun,AL,AL-505,".Calhoun County, Alabama",Calhoun,"118,408","117,744","117,190","116,471","115,917","115,469","114,973","114,710","114,331","113,605"
8,1017,Chambers,AL,AL-507,".Chambers County, Alabama",Chambers,"34,122","34,033","34,104","34,139","33,977","33,996","33,745","33,707","33,600","33,254"
9,1019,Cherokee,AL,AL-503,".Cherokee County, Alabama",Cherokee,"25,963","25,989","25,958","26,017","25,895","25,732","25,768","25,805","26,014","26,196"

In [5]:
unemployment_county_df = pd.read_csv('unemployment_data_clean.csv')
unemployment_county_df.head(10)

,FIPS_Code,State,Area_name,Unemployment_rate_2000,Unemployment_rate_2001,Unemployment_rate_2002,Unemployment_rate_2003,Unemployment_rate_2004,Unemployment_rate_2005,Unemployment_rate_2006,...,Unemployment_rate_2013,Unemployment_rate_2014,Unemployment_rate_2015,Unemployment_rate_2016,Unemployment_rate_2017,Unemployment_rate_2018,Unemployment_rate_2019,Unemployment_rate_2020,Median_Household_Income_2019,Med_HH_Income_Percent_of_State_Total_2019
0,0,US,United States,4.0,4.7,5.8,6.0,5.5,5.1,4.6,...,7.4,6.2,5.3,4.9,4.4,3.9,3.7,8.1,"65,712",NaN
1,1000,AL,Alabama,4.6,5.2,5.9,6.0,5.6,4.4,4.0,...,7.3,6.7,6.1,5.9,4.6,3.9,3.0,5.9,"51,771",100.0
2,1001,AL,"Autauga County, AL",4.1,4.1,4.8,5.0,4.7,3.8,3.3,...,6.3,5.8,5.2,5.1,4.0,3.6,2.7,4.9,"58,233",112.5
3,1003,AL,"Baldwin County, AL",3.7,4.3,5.0,4.9,5.1,4.0,3.2,...,6.7,6.1,5.6,5.4,4.2,3.6,2.8,5.6,"59,871",115.6
4,1005,AL,"Barbour County, AL",5.6,7.6,7.7,7.1,7.1,5.7,5.6,...,10.4,10.5,8.9,8.4,6.0,5.1,3.8,7.0,"35,972",69.5
5,1007,AL,"Bibb County, AL",5.4,6.8,7.0,5.9,5.4,4.4,4.2,...,8.0,7.2,6.7,6.5,4.5,4.0,3.1,6.6,"47,918",92.6
6,1009,AL,"Blount County, AL",3.5,3.7,5.4,4.6,4.1,3.6,3.2,...,6.4,6.1,5.4,5.4,4.2,3.5,2.7,4.1,"52,902",102.2
7,1011,AL,"Bullock County, AL",8.5,10.0,10.2,10.9,11.4,9.4,8.8,...,9.5,8.8,8.0,6.9,5.1,4.6,3.7,5.5,"31,906",61.6
8,1013,AL,"Butler County, AL",7.9,7.6,7.9,8.6,9.4,6.4,5.7,...,10.4,8.5,7.6,6.9,5.7,4.7,3.7,8.8,"39,944",77.2
9,1015,AL,"Calhoun County, AL",5.1,5.6,6.0,5.9,5.4,4.5,4.0,...,8.9,7.9,7.1,6.6,5.1,4.6,3.6,7.1,"47,747",92.2

In [ ]:
unemployment_data_clean.csv

In [6]:
county_main_df = pd.merge(county_coc_fips_df, unemployment_county_df, left_on=['FIPS'], right_on=['FIPS_Code'], how='left')
county_main_df.head(10)

,FIPS,county,state,number,Geographic Area,County,2010_population,2011_population,2012_population,2013_population,...,Unemployment_rate_2013,Unemployment_rate_2014,Unemployment_rate_2015,Unemployment_rate_2016,Unemployment_rate_2017,Unemployment_rate_2018,Unemployment_rate_2019,Unemployment_rate_2020,Median_Household_Income_2019,Med_HH_Income_Percent_of_State_Total_2019
0,1001,Autauga,AL,AL-507,".Autauga County, Alabama",Autauga,"54,773","55,227","54,954","54,727",...,6.3,5.8,5.2,5.1,4.0,3.6,2.7,4.9,"58,233",112.5
1,1003,Baldwin,AL,AL-501,".Baldwin County, Alabama",Baldwin,"183,112","186,558","190,145","194,885",...,6.7,6.1,5.6,5.4,4.2,3.6,2.8,5.6,"59,871",115.6
2,1005,Barbour,AL,AL-507,".Barbour County, Alabama",Barbour,"27,327","27,341","27,169","26,937",...,10.4,10.5,8.9,8.4,6.0,5.1,3.8,7.0,"35,972",69.5
3,1007,Bibb,AL,AL-507,".Bibb County, Alabama",Bibb,"22,870","22,745","22,667","22,521",...,8.0,7.2,6.7,6.5,4.5,4.0,3.1,6.6,"47,918",92.6
4,1009,Blount,AL,AL-503,".Blount County, Alabama",Blount,"57,376","57,560","57,580","57,619",...,6.4,6.1,5.4,5.4,4.2,3.5,2.7,4.1,"52,902",102.2
5,1011,Bullock,AL,AL-507,".Bullock County, Alabama",Bullock,"10,876","10,675","10,606","10,549",...,9.5,8.8,8.0,6.9,5.1,4.6,3.7,5.5,"31,906",61.6
6,1013,Butler,AL,AL-507,".Butler County, Alabama",Butler,"20,932","20,866","20,670","20,356",...,10.4,8.5,7.6,6.9,5.7,4.7,3.7,8.8,"39,944",77.2
7,1015,Calhoun,AL,AL-505,".Calhoun County, Alabama",Calhoun,"118,408","117,744","117,190","116,471",...,8.9,7.9,7.1,6.6,5.1,4.6,3.6,7.1,"47,747",92.2
8,1017,Chambers,AL,AL-507,".Chambers County, Alabama",Chambers,"34,122","34,033","34,104","34,139",...,8.1,6.7,6.1,5.5,4.2,3.9,2.9,6.8,"42,015",81.2
9,1019,Cherokee,AL,AL-503,".Cherokee County, Alabama",Cherokee,"25,963","25,989","25,958","26,017",...,6.7,5.8,5.5,5.1,4.2,3.6,2.9,4.6,"45,982",88.8

In [7]:
county_main_df.to_csv("county_data.csv", index=False)